# Syncs rust workflow files to the github rust I maintain from rust/workflows
files:
  # workflows
  - src_file: python/workflows/release-please.yml
    dest_file: .github/workflows/release-please.yml
    commit_msg: "ci: update release-please workflow"
  - src_file: python/workflows/release.yml
    dest_file: .github/workflows/release.yml
    commit_msg: "ci: update release workflow"
  - src_file: python/workflows/pre-release.yml
    dest_file: .github/workflows/pre-release.yml
    commit_msg: "ci: update pre-release workflow"
  - src_file: python/workflows/tests.yml
    dest_file: .github/workflows/tests.yml
    commit_msg: "ci: update tests workflow"
  - src_file: python/workflows/labeler.yml
    dest_file: .github/workflows/labeler.yml
    commit_msg: "ci: update labeler workflow"
  # dotfiles
  - src_file: python/dot-files/.flake8
    dest_file: .flake8
    commit_msg: "ci: update .flake8"
  - src_file: python/dot-files/.pre-commit-config.yaml
    dest_file: .pre-commit-config.yaml
    commit_msg: "ci: update .pre-commit-config.yaml"
  - src_file: python/dot-files/.prettierignore
    dest_file: .prettierignore
    commit_msg: "ci: update .prettierignore"
  - src_file: python/dot-files/labels.yml
    dest_file: .github/labels.yml
    commit_msg: "ci: update .github/labels.yml"
  # Dependabot
  - src_file: python/dot-files/dependabot.yml
    dest_file: .github/dependabot.yml
    commit_msg: "ci: update dependabot.yml"
