version: 2
updates:
  - package-ecosystem: "github_actions" 
    directory: "/.github/workflows" 
    schedule:
      interval: "daily"
  - package-ecosystem: "github_actions"
    directory: "/workflows" #
    schedule:
      interval: "daily"
