name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ secrets.THIS_PAT }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.9"
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: pip install pre-commit
      - name: Run Pre-commit
        uses: pre-commit/action@v3.0.0
