name: Repo Manager Master Settings Sync
# Syncs master settings to most repos.
on:
  workflow_dispatch:
    inputs:
      repo:
        description: Repo Name to run on
        required: false
        default: all
jobs:
  master-settings-sync:
    strategy:
      matrix:
        repo:
          - andrewthetechie
          - complexity-docker
          - geekbot-api-py
          - gha-clone-releases
          - gha-cookiecutter
          - gha-repo-manager
          - healthchecksio-check-k8s-operator
          - py-healthchecks.io
          - pydantic-aioredis
          - pydantic-pynamodb
          - sns-sub-manager
          - dd-metric
          - dd-event-rs
          - download-gha-logs-rs
          - pydantic-sqs
          - route53-operator
          - k8s-autoannotator
          - tf-vars-to-pydantic
          - cookiecutter-autodocs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        if: matrix.repo == inputs.repo || inputs.repo == 'all'
      - name: Run RepoManager Master Settings
        uses: andrewthetechie/gha-repo-manager@v1.6.0
        if: matrix.repo == inputs.repo || inputs.repo == 'all'
        env:
          THIS_PAT: ${{ secrets.THIS_PAT }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DISCORD_WEBHOOK_ISSUES: ${{ secrets.DISCORD_WEBHOOK_ISSUES }}
        with:
          # Apply your settings to the repo, can also be check to just check repo settings vs your file or validate, to validate your
          # file is valid
          action: apply
          settings_file: .github/rm-config/master-settings.yml
          # need a PAT that can edit repo settings
          token: ${{ secrets.THIS_PAT }}
          repo: andrewthetechie/${{ matrix.repo }}
