name: Sync Workflows to Actions Repos
on: [workflow_dispatch]
jobs:
  workflow-sync:
    strategy:
      matrix:
        repo:
          - gha-clone-releases
          - gha-cookiecutter
          - gha-repo-manager
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout
    - name: Run RepoManager
      uses: andrewthetechie/gha-repo-manager@v1.1.0
      with:
        # Apply your settings to the repo, can also be check to just check repo settings vs your file or validate, to validate your
        # file is valid
        action: apply
        settings_file: .github/workflow_sync/actions.yml
        # need a PAT that can edit repo settings
        token: ${{ secrets.THIS_PAT }}
        repo: andrewthetechie/${{ matrix.repo }}
